import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hospital Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <main className="mx-auto px-4 pb-16 pt-6 md:pt-10" style={{ maxWidth: "1100px" }}>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
